-- MySQL Script generated by MySQL Workbench
-- ven. 29 mai 2020 15:05:39 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Buddy_REC
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Buddy_REC` ;

-- -----------------------------------------------------
-- Schema Buddy_REC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Buddy_REC` DEFAULT CHARACTER SET utf8 ;
USE `Buddy_REC` ;

-- -----------------------------------------------------
-- Table `Buddy_REC`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Buddy_REC`.`user` (
  `pk_user` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(45) NOT NULL,
  `user_nom` VARCHAR(45) NOT NULL,
  `user_prenom` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_user`),
  UNIQUE INDEX `USER_EMAIL_UNIQUE` (`user_email` ASC),
  UNIQUE INDEX `user_password_UNIQUE` (`user_password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buddy_REC`.`moyen_paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Buddy_REC`.`moyen_paiement` (
  `pk_moyen_paiement` INT NOT NULL AUTO_INCREMENT,
  `moyen_paiement_type` VARCHAR(45) NOT NULL,
  `fk_user` INT NOT NULL,
  PRIMARY KEY (`pk_moyen_paiement`),
  INDEX `fk_MOYEN_PAIEMENT_1_idx` (`fk_user` ASC),
  CONSTRAINT `fk_MOYEN_PAIEMENT_1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `Buddy_REC`.`user` (`pk_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buddy_REC`.`rib`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Buddy_REC`.`rib` (
  `pk_rib` INT NOT NULL AUTO_INCREMENT,
  `rib_nom` VARCHAR(45) NOT NULL,
  `rib_number` VARCHAR(45) NOT NULL,
  `fk_moyen_paiement` INT NOT NULL,
  PRIMARY KEY (`pk_rib`),
  INDEX `fk_RIB_1_idx` (`fk_moyen_paiement` ASC),
  CONSTRAINT `fk_RIB_1`
    FOREIGN KEY (`fk_moyen_paiement`)
    REFERENCES `Buddy_REC`.`moyen_paiement` (`pk_moyen_paiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buddy_REC`.`cb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Buddy_REC`.`cb` (
  `pk_cb` INT NOT NULL AUTO_INCREMENT,
  `cb_nom` VARCHAR(45) NOT NULL,
  `cb_number` VARCHAR(45) NOT NULL,
  `cb_validite` VARCHAR(45) NOT NULL,
  `fk_moyen_paiement` INT NOT NULL,
  PRIMARY KEY (`pk_cb`),
  INDEX `fk_CB_1_idx` (`fk_moyen_paiement` ASC),
  CONSTRAINT `fk_CB_1`
    FOREIGN KEY (`fk_moyen_paiement`)
    REFERENCES `Buddy_REC`.`moyen_paiement` (`pk_moyen_paiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buddy_REC`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Buddy_REC`.`transactions` (
  `pk_transaction` INT NOT NULL AUTO_INCREMENT,
  `transaction_date` TIMESTAMP NOT NULL,
  `transaction_user_payeur` INT NOT NULL,
  `transaction_user_paye` INT NOT NULL,
  `transaction_montant` DOUBLE NOT NULL,
  `transaction_paye` DOUBLE NOT NULL,
  `transaction_prelevement` DOUBLE NOT NULL,
  `transaction_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_transaction`),
  INDEX `fk_TRANSACTIONS_1_idx` (`transaction_user_payeur` ASC),
  INDEX `fk_TRANSACTIONS_2_idx` (`transaction_user_paye` ASC),
  CONSTRAINT `fk_TRANSACTIONS_1`
    FOREIGN KEY (`transaction_user_payeur`)
    REFERENCES `Buddy_REC`.`user` (`pk_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSACTIONS_2`
    FOREIGN KEY (`transaction_user_paye`)
    REFERENCES `Buddy_REC`.`user` (`pk_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Buddy_REC`.`amis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Buddy_REC`.`amis` (
  `pk_amis` INT NOT NULL AUTO_INCREMENT,
  `amis_user` INT NOT NULL,
  `amis_amis` INT NOT NULL,
  INDEX `fk_Amis_1_idx` (`amis_user` ASC),
  INDEX `fk_Amis_2_idx` (`amis_amis` ASC),
  PRIMARY KEY (`pk_amis`),
  CONSTRAINT `fk_Amis_1`
    FOREIGN KEY (`amis_user`)
    REFERENCES `Buddy_REC`.`user` (`pk_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Amis_2`
    FOREIGN KEY (`amis_amis`)
    REFERENCES `Buddy_REC`.`user` (`pk_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
